export const ADD_BRAND_INIT = 'ADD_BRAND_INIT';
export const ADD_BRAND_SUCCESS = 'ADD_BRAND_SUCCESS';
export const ADD_BRAND__FAIL = 'ADD_BRAND__FAIL';

export const UPDATE_BRAND_INIT = 'UPDATE_BRAND_INIT';
export const UPDATE_BRAND_SUCCESS = 'UPDATE_BRAND_SUCCESS';
export const UPDATE_BRAND_FAIL = 'UPDATE_BRAND_FAIL';

export const GET_BRANDS_INIT = 'GET_BRANDS_INIT';
export const GET_BRANDS_SUCCESS = 'GET_BRANDS_SUCCESS';
export const GET_BRANDS__FAIL = 'GET_BRANDS__FAIL';

export const GET_BRAND_INIT = 'GET_BRAND_INIT';
export const GET_BRAND_SUCCESS = 'GET_BRAND_SUCCESS';
export const GET_BRAND__FAIL = 'GET_BRAND__FAIL';

export const DELETE_BRAND_INIT = 'DELETE_BRAND_INIT';
export const DELETE_BRAND_SUCCESS = 'DELETE_BRAND_SUCCESS';
export const DELETE_BRAND_FAIL = 'DELETE_BRAND_FAIL';
