export const ADD_PRODUCT_TO_CART_INIT = 'ADD_PRODUCT_TO_CART_INIT';
export const ADD_PRODUCT_TO_CART_SUCCESS = 'ADD_PRODUCT_TO_CART_SUCCESS';
export const ADD_PRODUCT_TO_CART_FAIL = 'ADD_PRODUCT_TO_CART_FAIL';

export const GET_PRODUCTS_CART_INIT = 'GET_PRODUCTS_CART_INIT';
export const GET_PRODUCTS_CART_SUCCESS = 'GET_PRODUCTS_CART_SUCCESS';
export const GET_PRODUCTS_CART_FAIL = 'GET_PRODUCTS_CART_FAIL';

export const DELETE_PRODUCT_FROM_CART_INIT = 'DELETE_PRODUCT_FROM_CART_INIT';
export const DELETE_PRODUCT_FROM_CART_SUCCESS = 'DELETE_PRODUCT_FROM_CART_SUCCESS';
export const DELETE_PRODUCT_FROM_CART_FAIL = 'DELETE_PRODUCT_FROM_CART_FAIL';

export const CHANGE_PRODUCT_QTY_INIT = 'CHANGE_PRODUCT_QTY_INIT';
export const CHANGE_PRODUCT_QTY_SUCCESS = 'CHANGE_PRODUCT_QTY_SUCCESS';
export const CHANGE_PRODUCT_QTY_FAIL = 'CHANGE_PRODUCT_QTY_FAIL';
