export const ADD_ORDER_INIT = 'ADD_ORDER_INIT';
export const ADD_ORDER_SUCCESS = 'ADD_ORDER_SUCCESS';
export const ADD_ORDER__FAIL = 'ADD_ORDER__FAIL';

export const GET_ORDER_INIT = 'GET_ORDER_INIT';
export const GET_ORDER_SUCCESS = 'GET_ORDER_SUCCESS';
export const GET_ORDER__FAIL = 'GET_ORDER__FAIL';

export const GET_PROVINCE_INIT = 'GET_PROVINCE_INIT';
export const GET_PROVINCE_SUCCESS = 'GET_PROVINCE_SUCCESS';
export const GET_PROVINCE_FAIL = 'GET_PROVINCE_FAIL';

export const GET_CITY_INIT = 'GET_CITY_INIT';
export const GET_CITY_SUCCESS = 'GET_CITY_SUCCESS';
export const GET_CITY_FAIL = 'GET_CITY_FAIL';

export const GET_COST_INIT = 'GET_COST_INIT';
export const GET_COST_SUCCESS = 'GET_COST_SUCCESS';
export const GET_COST_FAIL = 'GET_COST_FAIL';
