export const ADD_ORDER_INIT = 'ADD_ORDER_INIT';
export const ADD_ORDER_SUCCESS = 'ADD_ORDER_SUCCESS';
export const ADD_ORDER__FAIL = 'ADD_ORDER__FAIL';

export const GET_ORDER_INIT = 'GET_ORDER_INIT';
export const GET_ORDER_SUCCESS = 'GET_ORDER_SUCCESS';
export const GET_ORDER__FAIL = 'GET_ORDER__FAIL';

export const GET_ORDER_BY_ID_INIT = 'GET_ORDER_BY_ID_INIT';
export const GET_ORDER_BY_ID_SUCCESS = 'GET_ORDER_BY_ID_SUCCESS';
export const GET_ORDER_BY_ID_FAIL = 'GET_ORDER_BY_ID_FAIL';

export const GET_PAYMENT_INIT = 'GET_PAYMENT_INIT';
export const GET_PAYMENT_SUCCESS = 'GET_PAYMENT_SUCCESS';
export const GET_PAYMENT__FAIL = 'GET_PAYMENT__FAIL';

export const GET_PROVINCE_INIT = 'GET_PROVINCE_INIT';
export const GET_PROVINCE_SUCCESS = 'GET_PROVINCE_SUCCESS';
export const GET_PROVINCE_FAIL = 'GET_PROVINCE_FAIL';

export const GET_CITY_INIT = 'GET_CITY_INIT';
export const GET_CITY_SUCCESS = 'GET_CITY_SUCCESS';
export const GET_CITY_FAIL = 'GET_CITY_FAIL';

export const GET_COURIER_INIT = 'GET_COURIER_INIT';
export const GET_COURIER_SUCCESS = 'GET_COURIER_SUCCESS';
export const GET_COURIER_FAIL = 'GET_COURIER_FAIL';

export const RESET_ORDER = 'RESET_ORDER';
