// export const ADD_REVIEW_INIT = 'ADD_REVIEW_INIT';
// export const ADD_REVIEW_SUCCESS = 'ADD_REVIEW_SUCCESS';
// export const ADD_REVIEW_FAIL = 'ADD_REVIEW_FAIL';

// export const EDIT_REVIEW_INIT = 'EDIT_REVIEW_INIT';
// export const EDIT_REVIEW_SUCCESS = 'EDIT_REVIEW_SUCCESS';
// export const EDIT_REVIEW_FAIL = 'EDIT_REVIEW_FAIL';

// export const DELETE_REVIEW_INIT = 'DELETE_REVIEW_INIT';
// export const DELETE_REVIEW_SUCCESS = 'DELETE_REVIEW_SUCCESS';
// export const DELETE_REVIEW_FAIL = 'DELETE_REVIEW_FAIL';
