export const ADD_UNIT_INIT = 'ADD_UNIT_INIT';
export const ADD_UNIT_SUCCESS = 'ADD_UNIT_SUCCESS';
export const ADD_UNIT_FAIL = 'ADD_UNIT_FAIL';

export const GET_UNIT_INIT = 'GET_UNIT_INIT';
export const GET_UNIT_SUCCESS = 'GET_UNIT_SUCCESS';
export const GET_UNIT_FAIL = 'GET_CATEGOIES_FAIL';

export const RESET_STATE_UNIT = 'RESET_STATE_UNIT';
