export const SIGN_UP_INIT = 'SIGN_UP_INIT';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP__FAIL = 'SIGN_UP__FAIL';

export const SIGN_IN_INIT = 'SIGN_IN_INIT';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN__FAIL = 'SIGN_IN__FAIL';

export const SIGN_OUT_INIT = 'SIGN_OUT_INIT';
export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';
export const SIGN_OUT__FAIL = 'SIGN_OUT__FAIL';

export const RESET_PASSWORD_INIT = 'RESET_PASSWORD_INIT';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD__FAIL = 'RESET_PASSWORD__FAIL';

export const POST_NEW_PASSWORD_INIT = 'POST_NEW_PASSWORD_INIT';
export const POST_NEW_PASSWORD_SUCCESS = 'POST_NEW_PASSWORD_SUCCESS';
export const POST_NEW_PASSWORD__FAIL = 'POST_NEW_PASSWORD__FAIL';

export const GET_TOTAL_USERS_INIT = 'GET_TOTAL_USERS_INIT';
export const GET_TOTAL_USERS_SUCCESS = 'GET_TOTAL_USERS_SUCCESS';
export const GET_TOTAL_USERS_FAIL = 'GET_TOTAL_USERS_FAIL';

export const UPDATE_PROFILE_INIT = 'UPDATE_PROFILE_INIT';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAIL = 'UPDATE_PROFILE_FAIL';
