export const ADD_PRODUCT_TO_WISHLIST_INIT = 'ADD_PRODUCT_TO_WISHLIST_INIT';
export const ADD_PRODUCT_TO_WISHLIST_SUCCESS = 'ADD_PRODUCT_TO_WISHLIST_SUCCESS';
export const ADD_PRODUCT_TO_WISHLIST_FAIL = 'ADD_PRODUCT_TO_WISHLIST_FAIL';

export const DELETE_PRODUCT_FROM_WISHLIST_INIT = 'DELETE_PRODUCT_FROM_WISHLIST_INIT';
export const DELETE_PRODUCT_FROM_WISHLIST_SUCCESS = 'DELETE_PRODUCT_FROM_WISHLIST_SUCCESS';
export const DELETE_PRODUCT_FROM_WISHLIST_FAIL = 'DELETE_PRODUCT_FROM_WISHLIST_FAIL';

export const GET_PRODUCTS_WISHLIST_INIT = 'GET_PRODUCTS_WISHLIST_INIT';
export const GET_PRODUCTS_WISHLIST_SUCCESS = 'GET_PRODUCTS_WISHLIST_SUCCESS';
export const GET_PRODUCTS_WISHLIST_FAIL = 'GET_PRODUCTS_WISHLIST_FAIL';
