export const ADD_CATEGORY_INIT = 'ADD_CATEGORY_INIT';
export const ADD_CATEGORY_SUCCESS = 'ADD_CATEGORY_SUCCESS';
export const ADD_CATEGORY__FAIL = 'ADD_CATEGORY__FAIL';

export const UPDATE_CATEGORY_INIT = 'UPDATE_CATEGORY_INIT';
export const UPDATE_CATEGORY_SUCCESS = 'UPDATE_CATEGORY_SUCCESS';
export const UPDATE_CATEGORY_FAIL = 'UPDATE_CATEGORY_FAIL';

export const GET_CATEGORIES_INIT = 'GET_CATEGORIES_INIT';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES__FAIL = 'GET_CATEGOIES__FAIL';

export const GET_CATEGORY_INIT = 'GET_CATEGORY_INIT';
export const GET_CATEGORY_SUCCESS = 'GET_CATEGORY_SUCCESS';
export const GET_CATEGORY__FAIL = 'GET_CATEGORY__FAIL';

export const DELETE_CATEGORY_INIT = 'DELETE_CATEGORY_INIT';
export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS';
export const DELETE_CATEGORY_FAIL = 'DELETE_CATEGORY_FAIL';

export const RESET_STATUS_CATEGORY = 'RESET_STATUS_CATEGORY';
export const RESET_STATE_CATEGORY = 'RESET_STATE_CATEGORY';
