export const ADD_PRODUCT_INIT = 'ADD_PRODUCT_INIT';
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS';
export const ADD_PRODUCT__FAIL = 'ADD_PRODUCT__FAIL';

export const UPDATE_PRODUCT_INIT = 'UPDATE_PRODUCT_INIT';
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS';
export const UPDATE_PRODUCT_FAIL = 'UPDATE_PRODUCT_FAIL';

export const GET_PRODUCTS_INIT = 'GET_PRODUCTS_INIT';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS__FAIL = 'GET_PRODUCTS__FAIL';

export const GET_PRODUCT_BY_ID_INIT = 'GET_PRODUCT_BY_ID_INIT';
export const GET_PRODUCT_BY_ID_SUCCESS = 'GET_PRODUCT_BY_ID_SUCCESS';
export const GET_PRODUCT_BY_ID_FAIL = 'GET_PRODUCT_BY_ID_FAIL';

export const DELETE_PRODUCT_INIT = 'DELETE_PRODUCT_INIT';
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';
export const DELETE_PRODUCT_FAIL = 'DELETE_PRODUCT_FAIL';

export const RESET_STATUS_PRODUCT = 'RESET_STATUS_PRODUCT';

export const RESET_STATE_PRODUCT = 'RESET_STATE_PRODUCT';
